# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingSMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_sid', models.CharField(max_length=34)),
                ('account_sid', models.CharField(max_length=34)),
                ('from_number', models.CharField(max_length=30)),
                ('from_city', models.CharField(blank=True, default='', max_length=30)),
                ('from_state', models.CharField(blank=True, default='', max_length=30)),
                ('from_zip', models.CharField(blank=True, default='', max_length=30)),
                ('from_country', models.CharField(blank=True, default='', max_length=120)),
                ('to_number', models.CharField(max_length=30)),
                ('body', models.TextField(blank=True, default='', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Incoming SMS',
                'verbose_name_plural': 'Incoming SMS',
            },
        ),
        migrations.CreateModel(
            name='OutgoingSMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_sid', models.CharField(blank=True, default='', max_length=34)),
                ('account_sid', models.CharField(blank=True, default='', max_length=34)),
                ('from_number', models.CharField(max_length=30)),
                ('to_number', models.CharField(max_length=30)),
                ('to_parsed', models.CharField(blank=True, default='', max_length=30)),
                ('body', models.TextField(blank=True, default='', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_unit', models.CharField(blank=True, default='', max_length=3)),
            ],
            options={
                'verbose_name': 'Outgoing SMS',
                'verbose_name_plural': 'Outgoing SMS',
            },
        ),
    ]
